# Generated by Django 5.1.4 on 2024-12-13 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("in progress", "In progress"),
                    ("published", "Published"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
    ]
