# Generated by Django 5.1.4 on 2024-12-17 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_article_status'),
    ]

    operations = [
    ]


def create_superuser(apps, schema_editor)