# Generated by Django 5.1.4 on 2024-12-17 17:54
from django.utils import timezone
from django.db import migrations
from decouple import config


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_article_status'),
    ]

    operations = [
    ]


def create_superuser(apps, schema_editor):
    from django.contrib.auth import get_user_model

    User = get_user_model()

    if User.objects.exists():
        return 
    
    superuser = User.objects.create_superuser(
    username=config('username'),
    email=config('email'),
    password=config('password'),
    last_login=timezone.now()
    )
    superuser.save()

operations = [
    migrations.RunPython(create_superuser)
]